KLEI     1 return {
	override_enabled = true,
	worldgen_preset = "SURVIVAL_TOGETHER",
	settings_preset = "SURVIVAL_TOGETHER",
	overrides = {
		basicresource_regrowth = "always",
		beefaloheat = "rare",
		berrybush = "often",
		carrot = "often",
		carrots_regrowth = "fast",
		flint = "often",
		frograin = "rare",
		ghostsanitydrain = "none",
		grass = "often",
		portalresurection = "always",
		regrowth = "fast",
		resettime = "none",
		rock = "often",
		sapling = "often",
		weather = "rare",
		wildfires = "rare",
		world_size = "huge",
		worldseed = 1622020197,
	},
}